title: Dexter Nguyen # your name (or website title) here
logo: "/images/1.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  I am currently an analytics master student at Duke University 
  <br><br>
  I am passionate about using data analytics to solve complex business problems 
  <br><br>
  <a href="https://www.linkedin.com/in/dextertinhnguyen/">View My LinkedIn Profile</a>
  <a href="https://public.tableau.com/profile/dexter.nguyen8612#!/">View My Public Tableau Profile</a>
  
theme: jekyll-theme-minimal
